#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Registry host kernel/network tuning
#
# Applies the validated sysctl tuning that mitigates registry connection drops
# during many/large image pushes (see docs/harbor-registry-disconnect.md).
# Values were derived from a real K8s/flannel-vxlan host (RHEL 9.6, .81).
#
# Safe by design:
#   * additive sysctl drop-in (/etc/sysctl.d/99-registry-tuning.conf)
#   * --dry-run shows current -> target for every key, changes nothing
#   * --rollback removes the drop-in and reloads
#   * confirmation prompt unless --yes
#   * tolerant: a key the kernel doesn't expose (e.g. conntrack module not
#     loaded) is warned about, not fatal
###############################################################################

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
step()  { echo -e "\n${BLUE}══════ $* ══════${NC}"; }

DROPIN=/etc/sysctl.d/99-registry-tuning.conf
NOFILE_DROPIN=/etc/systemd/system/containerd.service.d/limits.conf
ACTION=apply
ASSUME_YES=false
DO_NOFILE=true
RUNTIME_SERVICE=containerd

usage() {
  cat <<EOF
Usage: tune-registry-kernel.sh [--apply|--dry-run|--rollback|--verify] [options]

Actions (default: --apply):
  --apply        Write the sysctl drop-in and apply it
  --dry-run      Show current -> target for each key; change nothing
  --rollback     Remove the drop-in (${DROPIN}) and reload defaults
  --verify       Print the current live value of each tuned key

Options:
  --no-nofile         Skip raising LimitNOFILE for ${RUNTIME_SERVICE}
  --service NAME      Runtime service to raise nofile on (default: ${RUNTIME_SERVICE})
  --yes               Do not prompt for confirmation
  -h, --help          Show this help
EOF
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply)    ACTION=apply; shift ;;
    --dry-run)  ACTION=dryrun; shift ;;
    --rollback) ACTION=rollback; shift ;;
    --verify)   ACTION=verify; shift ;;
    --no-nofile) DO_NOFILE=false; shift ;;
    --service)  RUNTIME_SERVICE="$2"; NOFILE_DROPIN="/etc/systemd/system/${2}.service.d/limits.conf"; shift 2 ;;
    --yes)      ASSUME_YES=true; shift ;;
    -h|--help)  usage ;;
    *)          error "Unknown option: $1" ;;
  esac
done

# key=value pairs (validated tuning)
read -r -d '' TUNING <<'EOF' || true
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.ipv4.tcp_rmem=4096 87380 16777216
net.ipv4.tcp_wmem=4096 65536 16777216
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_keepalive_time=600
net.ipv4.tcp_keepalive_intvl=30
net.ipv4.tcp_keepalive_probes=5
net.ipv4.tcp_mtu_probing=1
net.ipv4.ip_local_port_range=1024 65000
net.core.somaxconn=32768
net.core.netdev_max_backlog=16384
net.netfilter.nf_conntrack_max=1048576
EOF

cur() { sysctl -n "$1" 2>/dev/null | tr '\t' ' ' | sed 's/  */ /g'; }

show_table() {
  printf "%-42s %-22s %-22s\n" "KEY" "CURRENT" "TARGET"
  while IFS='=' read -r k v; do
    [[ -z "$k" ]] && continue
    local c; c=$(cur "$k"); [[ -z "$c" ]] && c="(not present)"
    printf "%-42s %-22s %-22s\n" "$k" "$c" "$v"
  done <<< "$TUNING"
}

[[ $EUID -eq 0 ]] || error "Run as root (sudo)."

case "$ACTION" in
  verify)
    step "Current live values"
    show_table
    [[ -f "$DROPIN" ]] && info "Drop-in present: $DROPIN" || warn "Drop-in not installed: $DROPIN"
    exit 0
    ;;

  dryrun)
    step "DRY RUN — current vs target (nothing will change)"
    show_table
    echo; info "Would write: $DROPIN"
    [[ "$DO_NOFILE" == true ]] && info "Would set LimitNOFILE=1048576 in $NOFILE_DROPIN and restart $RUNTIME_SERVICE"
    exit 0
    ;;

  rollback)
    step "Rollback"
    if [[ -f "$DROPIN" ]]; then rm -f "$DROPIN"; info "Removed $DROPIN"; else warn "No $DROPIN to remove"; fi
    if [[ -f "$NOFILE_DROPIN" ]]; then rm -f "$NOFILE_DROPIN"; systemctl daemon-reload; info "Removed $NOFILE_DROPIN (restart $RUNTIME_SERVICE to fully revert nofile)"; fi
    sysctl --system >/dev/null 2>&1 || true
    info "Reloaded sysctl defaults. Note: runtime values already changed in this boot persist until reboot or manual reset."
    exit 0
    ;;

  apply)
    step "Apply registry kernel tuning"
    show_table
    if [[ "$ASSUME_YES" != true ]]; then
      echo; read -rp "Apply the TARGET values above and persist them? [y/N] " a
      [[ "$a" =~ ^[Yy] ]] || { warn "aborted"; exit 0; }
    fi

    # Persist
    { echo "# Registry host tuning — see docs/harbor-registry-disconnect.md"
      echo "# Generated by tune-registry-kernel.sh"
      while IFS='=' read -r k v; do [[ -z "$k" ]] && continue; echo "${k} = ${v}"; done <<< "$TUNING"
    } > "$DROPIN"
    info "Wrote $DROPIN"

    # Apply each key now, tolerant of missing keys
    local_failed=0
    while IFS='=' read -r k v; do
      [[ -z "$k" ]] && continue
      if sysctl -w "${k}=${v}" >/dev/null 2>&1; then
        info "set ${k} = ${v}"
      else
        warn "could not set ${k} (key not exposed on this kernel?) — left in drop-in for next boot"
        local_failed=$((local_failed + 1))
      fi
    done <<< "$TUNING"

    if [[ "$DO_NOFILE" == true ]]; then
      mkdir -p "$(dirname "$NOFILE_DROPIN")"
      printf '[Service]\nLimitNOFILE=1048576\n' > "$NOFILE_DROPIN"
      systemctl daemon-reload
      info "Wrote $NOFILE_DROPIN (LimitNOFILE=1048576)."
      warn "Restart ${RUNTIME_SERVICE} in a maintenance window to apply nofile: systemctl restart ${RUNTIME_SERVICE}"
    fi

    echo
    info "Done. ${local_failed} key(s) deferred to next boot. Verify with: $0 --verify"
    ;;
esac
