FROM ubuntu:22.04
RUN apt-get update && apt-get install -y \
    openssl curl git docker.io jq \
    && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 https://github.com/bats-core/bats-core.git /opt/bats \
    && ln -s /opt/bats/bin/bats /usr/local/bin/bats \
    && git clone --depth 1 https://github.com/bats-core/bats-support.git /opt/bats-support \
    && git clone --depth 1 https://github.com/bats-core/bats-assert.git /opt/bats-assert
WORKDIR /workspace
COPY . /workspace/
